# Generated by Django 4.1.5 on 2023-01-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("picture", models.ImageField(upload_to="alumns/")),
                ("current_industry_position", models.CharField(max_length=255)),
                ("hall_of_residence", models.CharField(max_length=255)),
                ("year_of_graduation", models.DateField()),
            ],
        ),
    ]
