# Generated by Django 4.1.5 on 2023-01-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_rename_alumn_alum"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Alum",
            new_name="Alumn",
        ),
    ]
