# Generated by Django 4.1.5 on 2023-01-29 07:02

import authentication.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_alumn_year_of_graduation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumn",
            name="year_of_graduation",
            field=models.PositiveIntegerField(
                default=2023,
                validators=[
                    django.core.validators.MinValueValidator(1950),
                    authentication.models.max_value_current_year,
                ],
            ),
        ),
    ]
